"""Deterministic onboarding state machine.

Each state is a class with:
  - async enter(user, db, wa, phone) — send the prompt for this step
  - async process(message_text, media_urls, media_types, user, db, wa, phone, onboarding_state) —
        handle user response; returns next state name (str) or None to stay in current state

State names match OnboardingState.step values stored in the DB.

All user-facing messages are generated by Gemini (for natural Darija/French/Arabic).
All responses are routed through the dispatcher (voice or text per user preference).
"""

import base64
import json
import logging
from abc import ABC, abstractmethod

from app.agent.gemini_client import gemini_chat
from app.db import crud
from app.db.models import User, OnboardingState as OnboardingStateModel
from app.vision.media import download_twilio_media
from app.onboarding.industry_questions import detect_industry, get_industry_questions
from app.messaging.dispatcher import send_response

logger = logging.getLogger(__name__)

MAX_IMAGE_ATTEMPTS = 3

# ─────────────────────────────────────────────
# AI response helper
# ─────────────────────────────────────────────

ONBOARDING_SYSTEM = """You are a WhatsApp message generator for Anapec AI, a Moroccan career assistant.

You receive a JSON object with "task" and optional "data". You output ONLY the raw WhatsApp message text.
Nothing else — no prefixes, no labels, no explanations, no "Here is the message:".

DARIJA (when lang=darija):
- LATIN SCRIPT with numbers: 3=ع, 7=ح, 9=ق, 5=خ, 8=غ, 2=ء
- Mix French naturally like real Moroccans: CV, experience, diplome, entreprise, poste, stage, photo
- Real Darija expressions: wach, bghiti, sifet, chno, fach, 3lach, daba, yallah, wakha, safi, tbarkllah, mezyan, ghadi, khass, bzzaf, hani
- Sound like a smart Moroccan friend texting on WhatsApp. NEVER formal. NEVER MSA.
- 2-4 lines MAX.

When lang=fr: natural conversational French. When lang=ar: Modern Standard Arabic.

EXAMPLES:

Input: {"task": "confirm CIN data", "data": {"Nom": "TAZI MOHAMMED", "CIN": "AB123456", "Date": "15/03/1995"}, "lang": "darija"}
Output: Hak dak shi li 9rit mn l-CIN dyalk:
- *Smiya*: TAZI MOHAMMED
- *CIN*: AB123456
- *Tarikh l-izdiad*: 15/03/1995
Wach kolshi s7i7? Ila kayn chi ghalat gouliya.

Input: {"task": "ask for CIN front photo or skip", "lang": "darija"}
Output: Sifet liya tswira dyal l-CIN dyalk, l-wajh li fih smitk w l-numero. Ila mabghitich, goul skip.

Input: {"task": "ask about education/diplomas", "lang": "darija"}
Output: Daba nhdro 3la les diplomes dyalk. Sifet tswira dyal diplome wla gouliya: chno l-diplome, fin 9ritih, w f ina 3am. Yallah!

Input: {"task": "ask about professional experience, push for details", "lang": "darija"}
Output: Mezyan! Daba ndwiw 3la l-experience dyalk.
Gouliya 3la akher khdma drti: chno l-poste, smiyt l-charika, chhal d l-we9t, w chno konti kadir bdebt?

Input: {"task": "photo not clear, try again, attempt 2/3", "lang": "darija"}
Output: Sma7 li, had tswira machi wad7a bzzaf. 3afak sifet we7da khra, khass l-ktaba tkon katban mezyan. Hadi l-mo7awala 2/3.

Input: {"task": "corrections saved, moving on", "lang": "darija"}
Output: Safi, 9yedt dak shi. Yallah nkmlou!"""


async def respond(wa, phone: str, user, task: str, data: dict = None) -> None:
    """Generate a WhatsApp message via Gemini and send through dispatcher."""
    lang = getattr(user, "language", "darija") or "darija"
    input_obj = {"task": task, "lang": lang}
    if data:
        input_obj["data"] = data
    prompt = json.dumps(input_obj, ensure_ascii=False)

    try:
        text = await gemini_chat(
            system=ONBOARDING_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2048,
            temperature=0.7,
            thinking_budget=1024,
        )
        text = text.strip()
        if not text:
            text = task  # fallback
    except Exception as e:
        logger.error(f"Gemini respond failed: {e}", exc_info=True)
        logger.error(f"Gemini failed: {e}")
        text = task

    await send_response(phone, text, user, wa)


async def respond_raw(wa, phone: str, user, text: str) -> None:
    """Send a pre-built message through the dispatcher (voice/text)."""
    await send_response(phone, text, user, wa)


def _calc_completeness(user: User) -> int:
    """Calculate profile completeness as a percentage (0-100)."""
    score = 0
    total = 0

    total += 15
    if user.cin_number:
        score += 8
    if user.full_name_latin or user.full_name_arabic:
        score += 4
    if user.date_of_birth:
        score += 3

    total += 5
    if user.address:
        score += 3
    if user.gender:
        score += 2

    total += 20
    edu = user.education or []
    if edu:
        score += min(20, len(edu) * 10)

    total += 25
    exp = user.experience or []
    if exp:
        score += min(25, len(exp) * 8)

    total += 5
    if user.languages_spoken:
        score += 5

    total += 3
    if user.driving_license:
        score += 3

    total += 5
    if user.extracurricular:
        score += 5

    total += 7
    if user.photo_b64:
        score += 7

    total += 10
    if user.industry_category:
        score += 5
    if user.industry_details:
        score += 5

    total += 2
    if user.communication_pref:
        score += 2

    total += 3
    if user.language:
        score += 3

    return int((score / total) * 100) if total > 0 else 0


def _update_completeness(db, user: User):
    pct = _calc_completeness(user)
    crud.update_user(db, user, profile_completeness=pct)


async def _ocr_image(image_data: bytes, media_type: str, extraction_type: str) -> dict | None:
    """Run OCR via Claude vision on an image."""
    from app.agent.claude_client import chat_with_image
    from app.agent.prompts import CIN_FRONT_EXTRACTION, CIN_BACK_EXTRACTION, DIPLOMA_EXTRACTION

    prompt_map = {
        "cin_front": CIN_FRONT_EXTRACTION,
        "cin_back": CIN_BACK_EXTRACTION,
        "diploma": DIPLOMA_EXTRACTION,
    }
    system_prompt = prompt_map.get(extraction_type, CIN_FRONT_EXTRACTION)

    try:
        response = await chat_with_image(
            system=system_prompt,
            messages=[],
            image_data=image_data,
            media_type=media_type,
            max_tokens=1024,
        )
        text = response.strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()
        return json.loads(text)
    except Exception as e:
        logger.error(f"OCR ({extraction_type}) failed: {e}", exc_info=True)
        return None


async def _parse_json_response(response_text: str) -> dict | list | None:
    """Clean and parse a JSON response from Gemini."""
    text = response_text.strip()
    if "```" in text:
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()
    try:
        return json.loads(text)
    except Exception:
        return None


async def _classify_intent(user_message: str, intents: dict[str, str], context: str = "") -> str:
    """Use Gemini to classify user intent from a natural language message.

    Args:
        user_message: The raw user message (any language/dialect)
        intents: Dict mapping intent_name → description
        context: What the bot just asked / what we're expecting

    Returns:
        One of the intent names (keys of intents dict)
    """
    intent_list = "\n".join(f"- {k}: {v}" for k, v in intents.items())
    fallback = list(intents.keys())[-1]

    prompt = (
        f'User message: "{user_message}"\n'
        f'Context: {context}\n\n'
        f"Classify into exactly ONE of these intents:\n{intent_list}\n\n"
        f"Return ONLY the intent name, nothing else."
    )

    try:
        response = await gemini_chat(
            system="You are an intent classifier for a Moroccan WhatsApp bot. "
                   "Users speak Darija (Latin script with numbers: 3=ع, 7=ح, 9=ق), French, or Arabic. "
                   "Return ONLY the intent label — one word, no quotes, no explanation.",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=256,
            temperature=0.0,
        )
        result = response.strip().lower().strip('"\'.,!:')
        for intent_name in intents:
            if intent_name.lower() in result:
                return intent_name
        return fallback
    except Exception as e:
        logger.error(f"Intent classification failed: {e}")
        return fallback


async def _parse_correction(user_message: str, ocr_result: dict, valid_fields: list[str]) -> dict | None:
    """Use Gemini to understand partial corrections from the user."""
    fields_str = json.dumps(ocr_result, ensure_ascii=False)
    prompt = f"""The user was shown these OCR-extracted fields:
{fields_str}

The user replied: "{user_message}"

Extract ONLY the fields they want to change. Valid field names: {valid_fields}
If the user says everything is correct, return {{}}.
If you can't understand, return null.
Return ONLY valid JSON."""

    try:
        response = await gemini_chat(
            system="You parse user corrections for OCR data. Return only valid JSON.",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=256,
            temperature=0.1,
        )
        result = await _parse_json_response(response)
        return result if isinstance(result, dict) else None
    except Exception as e:
        logger.error(f"Correction parsing failed: {e}", exc_info=True)
        return None


# ─────────────────────────────────────────────
# Base class
# ─────────────────────────────────────────────

class BaseState(ABC):
    name: str = ""

    @abstractmethod
    async def enter(self, user: User, db, wa, phone: str):
        ...

    @abstractmethod
    async def process(self, message_text: str, media_urls: list[str], media_types: list[str],
                      user: User, db, wa, phone: str, ob_state: OnboardingStateModel) -> str | None:
        ...


# ─────────────────────────────────────────────
# 1. WELCOME
# ─────────────────────────────────────────────

class WelcomeState(BaseState):
    name = "WELCOME"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Welcome the user to Anapec AI. Introduce yourself as their career assistant. "
            "Tell them you can help with: professional CV creation, job search, skills assessment (bilan des competences), "
            "and ANAPEC info. Ask them to say something so you can detect their language. "
            "Keep it warm and short. Write the welcome in BOTH Darija and French since we don't know their language yet.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        detected = await _classify_intent(message_text, {
            "darija": "Moroccan Darija — Arabic dialect, often Latin script with numbers (3,7,9,5,8)",
            "fr": "French language",
            "ar": "Modern Standard Arabic in Arabic script",
        }, context="Detect the language of this first message from a Moroccan user")

        crud.update_user(db, user, language=detected)

        step_data = dict(ob_state.step_data or {})
        step_data["detected_language"] = detected
        step_data["first_message"] = message_text[:200]
        crud.update_onboarding_state(db, ob_state, step_data=step_data)

        return "LANGUAGE_PREF"


# ─────────────────────────────────────────────
# 2. LANGUAGE_PREF
# ─────────────────────────────────────────────

class LanguagePrefState(BaseState):
    name = "LANGUAGE_PREF"

    async def enter(self, user, db, wa, phone):
        detected = user.language or "darija"
        lang_names = {"darija": "Darija", "fr": "Francais", "ar": "Arabe"}
        await respond(wa, phone, user,
            f"You detected the user speaks {lang_names.get(detected, 'Darija')}. "
            f"Ask them to confirm: 1. Darija  2. Francais  3. Arabe. "
            f"Keep it very short, just confirm the language.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        lang = await _classify_intent(message_text, {
            "darija": "User chose Darija (option 1, or said darija/darja/الدارجة)",
            "fr": "User chose French (option 2, or said francais/français/french)",
            "ar": "User chose Arabic (option 3, or said arabe/arabic/عربية/العربية)",
        }, context="User is choosing their preferred language: 1. Darija  2. Français  3. Arabe")

        crud.update_user(db, user, language=lang)
        _update_completeness(db, user)
        return "COMM_PREF"


# ─────────────────────────────────────────────
# 3. COMM_PREF (auto-sets voice, no question)
# ─────────────────────────────────────────────

class CommPrefState(BaseState):
    name = "COMM_PREF"

    async def enter(self, user, db, wa, phone):
        crud.update_user(db, user, communication_pref="voice")
        _update_completeness(db, user)
        await respond(wa, phone, user,
            "Confirm to the user that you'll respond with voice messages from now on. "
            "Tell them they can switch to text anytime by saying 'text'. "
            "Then tell them: now let's build your profile, starting with the CIN (national ID card). "
            "Ask them to send a photo of the FRONT of their CIN (the side with their name and number). "
            "If they don't want to, they can say 'skip' for manual entry.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        if media_urls:
            # User already sent a CIN photo — transition to CIN_FRONT and process it there
            crud.set_onboarding_step(db, user.id, "CIN_FRONT")
            crud.update_user(db, user, onboarding_step="CIN_FRONT")
            new_ob = crud.get_onboarding_state(db, user.id)
            cin_front = CINFrontState()
            result = await cin_front.process(message_text, media_urls, media_types, user, db, wa, phone, new_ob)
            return result  # None (awaiting confirm) or "CIN_BACK"
        return "CIN_FRONT"


# ─────────────────────────────────────────────
# 4. CIN_FRONT
# ─────────────────────────────────────────────

class CINFrontState(BaseState):
    name = "CIN_FRONT"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Ask the user to send a photo of the FRONT of their CIN (national ID card). "
            "The front side has their name, CIN number, and date of birth. "
            "If they prefer, they can type 'skip' for manual entry.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})

        # Awaiting confirmation of OCR results
        if step_data.get("awaiting_confirmation"):
            intent = await _classify_intent(message_text, {
                "confirm": "User confirms the extracted data is correct",
                "correct": "User wants to fix or change something in the data",
            }, context="Bot showed OCR-extracted CIN data (name, CIN number, date of birth) and asked if it's correct")

            if intent == "confirm":
                step_data.pop("awaiting_confirmation", None)
                crud.update_onboarding_state(db, ob_state, step_data=step_data)
                _update_completeness(db, user)
                return "CIN_BACK"

            # User wants corrections — parse what they want to change
            corrections = await _parse_correction(
                message_text,
                step_data.get("ocr_result", {}),
                ["full_name_latin", "full_name_arabic", "cin_number", "date_of_birth"],
            )
            if corrections:
                updates = {}
                for field, value in corrections.items():
                    if field == "full_name_latin":
                        updates["full_name_latin"] = value
                        updates["name"] = value
                    elif field == "full_name_arabic":
                        updates["full_name_arabic"] = value
                    elif field == "cin_number":
                        updates["cin_number"] = value
                    elif field == "date_of_birth":
                        updates["date_of_birth"] = value
                if updates:
                    crud.update_user(db, user, **updates)
                    _update_completeness(db, user)
                step_data.pop("awaiting_confirmation", None)
                crud.update_onboarding_state(db, ob_state, step_data=step_data)
                await respond(wa, phone, user,
                    "Confirm the corrections are saved. Say let's continue to the next step.")
                return "CIN_BACK"

            # Couldn't parse specific corrections — ask what to fix
            await respond(wa, phone, user,
                "Ask the user to specify exactly what needs to be corrected in the CIN data.")
            return None

        # Manual entry mode
        if step_data.get("manual_mode"):
            return await self._process_manual(message_text, user, db, wa, phone, ob_state, step_data)

        # Has media → OCR
        if media_urls:
            pass  # fall through to OCR below
        else:
            # No media — classify: skip or something else?
            intent = await _classify_intent(message_text, {
                "skip": "User wants to skip CIN photo and enter data manually",
                "other": "User is asking a question or saying something else",
            }, context="Bot asked for a photo of the front of their CIN (national ID card). User can skip for manual entry.")

            if intent == "skip":
                return await self._handle_manual(user, db, wa, phone, ob_state)

            attempts = ob_state.attempts + 1
            crud.update_onboarding_state(db, ob_state, attempts=attempts)
            if attempts >= MAX_IMAGE_ATTEMPTS:
                return await self._handle_manual(user, db, wa, phone, ob_state)
            await respond(wa, phone, user,
                f"Ask them to send a PHOTO of their CIN front. "
                f"Or they can say they want to skip. Attempt {attempts}/{MAX_IMAGE_ATTEMPTS}.")
            return None

        # Download and OCR
        try:
            image_data, content_type = await download_twilio_media(media_urls[0])
            result = await _ocr_image(image_data, content_type, "cin_front")

            if result and (result.get("cin_number") or result.get("full_name_latin")):
                updates = {}
                if result.get("cin_number"):
                    updates["cin_number"] = result["cin_number"]
                if result.get("full_name_latin"):
                    updates["full_name_latin"] = result["full_name_latin"]
                    updates["name"] = result["full_name_latin"]
                if result.get("full_name_arabic"):
                    updates["full_name_arabic"] = result["full_name_arabic"]
                if result.get("date_of_birth"):
                    updates["date_of_birth"] = result["date_of_birth"]

                cin_data = dict(user.cin_data or {})
                cin_data["front"] = result
                updates["cin_data"] = cin_data
                crud.update_user(db, user, **updates)
                _update_completeness(db, user)

                # Build data summary for the AI to present
                extracted = {}
                if result.get("full_name_latin"):
                    extracted["Nom"] = result["full_name_latin"]
                if result.get("cin_number"):
                    extracted["CIN"] = result["cin_number"]
                if result.get("date_of_birth"):
                    extracted["Date de naissance"] = result["date_of_birth"]
                if result.get("lieu_de_naissance"):
                    extracted["Lieu de naissance"] = result["lieu_de_naissance"]

                step_data["ocr_result"] = result
                step_data["awaiting_confirmation"] = True
                crud.update_onboarding_state(db, ob_state, step_data=step_data)

                await respond(wa, phone, user,
                    "Show the user the data below from their CIN. "
                    "Ask: is this correct? If something is wrong, tell me what to fix.",
                    data=extracted)
                return None
            else:
                attempts = ob_state.attempts + 1
                crud.update_onboarding_state(db, ob_state, attempts=attempts)
                if attempts >= MAX_IMAGE_ATTEMPTS:
                    return await self._handle_manual(user, db, wa, phone, ob_state)
                await respond(wa, phone, user,
                    f"The photo wasn't clear enough. Ask for a clearer photo of the CIN front. "
                    f"Attempt {attempts}/{MAX_IMAGE_ATTEMPTS}. Or say 'skip'.")
                return None

        except Exception as e:
            logger.error(f"CIN front processing error: {e}", exc_info=True)
            attempts = ob_state.attempts + 1
            crud.update_onboarding_state(db, ob_state, attempts=attempts)
            if attempts >= MAX_IMAGE_ATTEMPTS:
                return await self._handle_manual(user, db, wa, phone, ob_state)
            await respond(wa, phone, user,
                "There was a problem processing the image. Ask the user to resend or say 'skip'.")
            return None

    async def _handle_manual(self, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})
        step_data["manual_mode"] = True
        step_data["manual_step"] = "full_name"
        crud.update_onboarding_state(db, ob_state, step_data=step_data)
        await respond(wa, phone, user,
            "We'll enter the CIN info manually. Ask for their full name (in French or Arabic).")
        return None

    async def _process_manual(self, message_text, user, db, wa, phone, ob_state, step_data):
        text_val = message_text.strip()
        manual_step = step_data.get("manual_step", "full_name")

        if manual_step == "full_name":
            crud.update_user(db, user, full_name_latin=text_val, name=text_val)
            step_data["manual_step"] = "cin_number"
            crud.update_onboarding_state(db, ob_state, step_data=step_data)
            await respond(wa, phone, user,
                "Name saved. Now ask for their CIN number (format: 1-2 letters + digits, e.g., AB123456).")
            return None

        elif manual_step == "cin_number":
            crud.update_user(db, user, cin_number=text_val)
            step_data["manual_step"] = "date_of_birth"
            crud.update_onboarding_state(db, ob_state, step_data=step_data)
            await respond(wa, phone, user,
                "CIN number saved. Now ask for their date of birth (format: DD/MM/YYYY, e.g., 15/03/1995).")
            return None

        elif manual_step == "date_of_birth":
            crud.update_user(db, user, date_of_birth=text_val)
            _update_completeness(db, user)
            return "CIN_BACK"

        return None


# ─────────────────────────────────────────────
# 5. CIN_BACK
# ─────────────────────────────────────────────

class CINBackState(BaseState):
    name = "CIN_BACK"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Now ask for a photo of the BACK of their CIN (the side with the address). "
            "They can say 'skip' for manual entry.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})

        if step_data.get("awaiting_confirmation"):
            intent = await _classify_intent(message_text, {
                "confirm": "User confirms the extracted data is correct",
                "correct": "User wants to fix or change something in the data",
            }, context="Bot showed OCR-extracted CIN back data (address, city, gender) and asked if it's correct")

            if intent == "confirm":
                step_data.pop("awaiting_confirmation", None)
                crud.update_onboarding_state(db, ob_state, step_data=step_data)
                return "EDUCATION"

            corrections = await _parse_correction(
                message_text, step_data.get("ocr_result", {}),
                ["address", "city", "gender"],
            )
            if corrections:
                updates = {}
                for field, value in corrections.items():
                    if field in ("address", "city", "gender"):
                        updates[field] = value
                if updates:
                    crud.update_user(db, user, **updates)
                    _update_completeness(db, user)
                step_data.pop("awaiting_confirmation", None)
                crud.update_onboarding_state(db, ob_state, step_data=step_data)
                await respond(wa, phone, user, "Corrections saved. Let's continue to education.")
                return "EDUCATION"

            await respond(wa, phone, user,
                "Ask the user to specify exactly what needs to be corrected in the CIN back data.")
            return None

        if step_data.get("manual_mode"):
            return await self._process_manual(message_text, user, db, wa, phone, ob_state, step_data)

        if media_urls:
            pass  # fall through to OCR below
        else:
            intent = await _classify_intent(message_text, {
                "skip": "User wants to skip CIN back photo and enter data manually",
                "other": "User is asking a question or saying something else",
            }, context="Bot asked for a photo of the back of their CIN (address side). User can skip for manual entry.")

            if intent == "skip":
                return await self._handle_manual(user, db, wa, phone, ob_state)

            attempts = ob_state.attempts + 1
            crud.update_onboarding_state(db, ob_state, attempts=attempts)
            if attempts >= MAX_IMAGE_ATTEMPTS:
                return await self._handle_manual(user, db, wa, phone, ob_state)
            await respond(wa, phone, user,
                f"Ask them to send a PHOTO of their CIN back. "
                f"Or they can say they want to skip. Attempt {attempts}/{MAX_IMAGE_ATTEMPTS}.")
            return None

        try:
            image_data, content_type = await download_twilio_media(media_urls[0])
            result = await _ocr_image(image_data, content_type, "cin_back")

            if result and (result.get("address") or result.get("gender")):
                updates = {}
                if result.get("address"):
                    updates["address"] = result["address"]
                if result.get("city"):
                    updates["city"] = result["city"]
                if result.get("gender"):
                    updates["gender"] = result["gender"]

                cin_data = dict(user.cin_data or {})
                cin_data["back"] = result
                updates["cin_data"] = cin_data
                crud.update_user(db, user, **updates)
                _update_completeness(db, user)

                extracted = {}
                if result.get("address"):
                    extracted["Adresse"] = result["address"]
                if result.get("city"):
                    extracted["Ville"] = result["city"]
                if result.get("gender"):
                    extracted["Genre"] = "Homme" if result["gender"] == "M" else "Femme"

                step_data["ocr_result"] = result
                step_data["awaiting_confirmation"] = True
                crud.update_onboarding_state(db, ob_state, step_data=step_data)

                await respond(wa, phone, user,
                    "Show the user the data below from the back of their CIN. "
                    "Ask: is this correct? If something is wrong, tell me what to fix.",
                    data=extracted)
                return None
            else:
                attempts = ob_state.attempts + 1
                crud.update_onboarding_state(db, ob_state, attempts=attempts)
                if attempts >= MAX_IMAGE_ATTEMPTS:
                    return await self._handle_manual(user, db, wa, phone, ob_state)
                await respond(wa, phone, user,
                    f"Couldn't read the CIN back. Ask for a clearer photo. Attempt {attempts}/{MAX_IMAGE_ATTEMPTS}.")
                return None

        except Exception as e:
            logger.error(f"CIN back processing error: {e}", exc_info=True)
            attempts = ob_state.attempts + 1
            crud.update_onboarding_state(db, ob_state, attempts=attempts)
            if attempts >= MAX_IMAGE_ATTEMPTS:
                return await self._handle_manual(user, db, wa, phone, ob_state)
            await respond(wa, phone, user, "Problem with the image. Ask to resend or say 'skip'.")
            return None

    async def _handle_manual(self, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})
        step_data["manual_mode"] = True
        step_data["manual_step"] = "address"
        crud.update_onboarding_state(db, ob_state, step_data=step_data)
        await respond(wa, phone, user, "We'll enter manually. Ask for their full address.")
        return None

    async def _process_manual(self, message_text, user, db, wa, phone, ob_state, step_data):
        text_val = message_text.strip()
        manual_step = step_data.get("manual_step", "address")

        if manual_step == "address":
            crud.update_user(db, user, address=text_val)
            step_data["manual_step"] = "city"
            crud.update_onboarding_state(db, ob_state, step_data=step_data)
            await respond(wa, phone, user,
                "Address saved. Now ask which city they live in (e.g., Casablanca, Rabat, Fes...).")
            return None

        elif manual_step == "city":
            crud.update_user(db, user, city=text_val)
            step_data["manual_step"] = "gender"
            crud.update_onboarding_state(db, ob_state, step_data=step_data)
            await respond(wa, phone, user, "City saved. Now ask if they are male or female.")
            return None

        elif manual_step == "gender":
            text_lower = text_val.lower()
            if text_lower in ("m", "mra", "f", "femme", "female", "امرأة", "ا"):
                gender = "F"
            else:
                gender = "M"
            crud.update_user(db, user, gender=gender)
            _update_completeness(db, user)
            return "EDUCATION"

        return None


# ─────────────────────────────────────────────
# 6. EDUCATION
# ─────────────────────────────────────────────

class EducationState(BaseState):
    name = "EDUCATION"

    async def enter(self, user, db, wa, phone):
        name = user.full_name_latin or user.name or ""
        first_name = name.split()[0] if name else ""
        await respond(wa, phone, user,
            f"{'Address the user by ' + first_name + '. ' if first_name else ''}"
            "Now it's time to talk about their education/diplomas. "
            "They can send a PHOTO of a diploma (OCR will extract it) or describe it in text: "
            "degree name, field of study, institution, year. "
            "They can add multiple diplomas one by one. "
            "Be encouraging about this step - education is important for their CV.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})

        # If no media, classify intent
        if not media_urls:
            intent = await _classify_intent(message_text, {
                "done": "User is finished adding diplomas, or has no education at all",
                "content": "User is providing education/diploma information in text",
            }, context="Bot asked about education/diplomas. User can add multiple, send photos, or say done.")

            if intent == "done":
                _update_completeness(db, user)
                if not step_data.get("has_at_least_one"):
                    await respond(wa, phone, user,
                        "Acknowledge they have no diplomas to add. That's ok. Moving on to experience.")
                return "EXPERIENCE"

        # Process image (diploma OCR)
        if media_urls:
            try:
                image_data, content_type = await download_twilio_media(media_urls[0])
                result = await _ocr_image(image_data, content_type, "diploma")

                if result and (result.get("degree_name") or result.get("institution")):
                    diploma = {
                        "degree_name": result.get("degree_name", ""),
                        "field_of_study": result.get("field_of_study", ""),
                        "institution": result.get("institution", ""),
                        "city": result.get("city", ""),
                        "year": result.get("year", ""),
                        "honors": result.get("honors", ""),
                        "type": result.get("type", "diploma"),
                    }
                    edu_list = list(user.education or [])
                    edu_list.append(diploma)
                    crud.update_user(db, user, education=edu_list)
                    step_data["has_at_least_one"] = True
                    crud.update_onboarding_state(db, ob_state, step_data=step_data)

                    await respond(wa, phone, user,
                        "Show the diploma info below. Ask if they have another diploma to add, or say 'done'.",
                        data=diploma)
                    return None
                else:
                    await respond(wa, phone, user,
                        "Couldn't read the diploma image. Ask them to try a clearer photo or type the info instead.")
                    return None

            except Exception as e:
                logger.error(f"Diploma OCR error: {e}", exc_info=True)
                await respond(wa, phone, user,
                    "Problem with the diploma image. Ask them to describe their education in text.")
                return None

        # Process text entry
        if message_text.strip():
            diploma = await self._parse_education_text(message_text)
            edu_list = list(user.education or [])
            edu_list.append(diploma)
            crud.update_user(db, user, education=edu_list)
            step_data["has_at_least_one"] = True
            crud.update_onboarding_state(db, ob_state, step_data=step_data)

            await respond(wa, phone, user,
                "Show the education info below. Ask if they have another diploma to add, or say 'done'.",
                data=diploma)
            return None

        return None

    async def _parse_education_text(self, text: str) -> dict:
        try:
            response = await gemini_chat(
                system="Extract education/diploma info. Return ONLY valid JSON: "
                       '{"degree_name":"","field_of_study":"","institution":"","city":"","year":"","honors":"","type":"diploma"}',
                messages=[{"role": "user", "content": text}],
                max_tokens=512, temperature=0.1,
            )
            result = await _parse_json_response(response)
            return result if isinstance(result, dict) else {"degree_name": text.strip()[:200]}
        except Exception:
            return {"degree_name": text.strip()[:200], "field_of_study": "", "institution": "", "year": ""}


# ─────────────────────────────────────────────
# 7. EXPERIENCE
# ─────────────────────────────────────────────

class ExperienceState(BaseState):
    name = "EXPERIENCE"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Now let's talk about their professional experience. This is the MOST IMPORTANT part of their CV. "
            "Ask about their most recent job: title, company, duration, daily responsibilities, achievements. "
            "Be a coach — push for details. 'Worked in logistics' is not enough, we need specifics! "
            "If they have no experience, they can say so.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})

        # Drilling deeper into current job (don't classify intent during drill)
        if step_data.get("current_job") and step_data.get("drilling"):
            return await self._drill_deeper(message_text, user, db, wa, phone, ob_state, step_data)

        # Classify intent
        intent = await _classify_intent(message_text, {
            "done": "User is done adding jobs, or has no professional experience at all",
            "content": "User is describing a job, work experience, or professional activity",
        }, context="Bot asked about professional experience. User can describe jobs or say they have none/are done.")

        if intent == "done":
            _update_completeness(db, user)
            if not step_data.get("has_at_least_one"):
                await respond(wa, phone, user,
                    "Acknowledge they have no experience. That's ok, we'll work with what they have. Moving on.")
            return "EXTRACURRICULAR"

        # Parse experience
        job = await self._parse_experience_text(message_text)

        missing = []
        if not job.get("title"):
            missing.append("job title")
        if not job.get("company"):
            missing.append("company name")
        if not job.get("period"):
            missing.append("time period")
        if not job.get("responsibilities") or len(str(job.get("responsibilities", ""))) < 20:
            missing.append("detailed daily responsibilities")

        if missing:
            step_data["current_job"] = job
            step_data["drilling"] = True
            crud.update_onboarding_state(db, ob_state, step_data=step_data)

            await respond(wa, phone, user,
                f"The user gave some job info but we still need: {', '.join(missing)}. "
                f"Push for more details like a career coach — the CV depends on it! "
                f"Already collected: {json.dumps(job, ensure_ascii=False)}",
                data={"collected": job, "missing": missing})
            return None

        return await self._save_job(job, user, db, wa, phone, ob_state, step_data)

    async def _drill_deeper(self, message_text, user, db, wa, phone, ob_state, step_data):
        current_job = step_data.get("current_job", {})
        merged = await self._merge_experience(current_job, message_text)

        missing = []
        if not merged.get("title"):
            missing.append("job title")
        if not merged.get("responsibilities") or len(str(merged.get("responsibilities", ""))) < 20:
            missing.append("detailed responsibilities")

        if missing and ob_state.attempts < 3:
            step_data["current_job"] = merged
            crud.update_onboarding_state(db, ob_state, step_data=step_data, attempts=ob_state.attempts + 1)
            await respond(wa, phone, user,
                f"Thanks for the info! But still need: {', '.join(missing)}. "
                f"Push gently for more specifics. This makes the CV stand out.",
                data={"collected": merged, "still_missing": missing})
            return None

        return await self._save_job(merged, user, db, wa, phone, ob_state, step_data)

    async def _save_job(self, job, user, db, wa, phone, ob_state, step_data):
        exp_list = list(user.experience or [])
        exp_list.append(job)
        crud.update_user(db, user, experience=exp_list)

        step_data["has_at_least_one"] = True
        step_data.pop("current_job", None)
        step_data.pop("drilling", None)
        crud.update_onboarding_state(db, ob_state, step_data=step_data, attempts=0)

        await respond(wa, phone, user,
            "Show the job info below. Ask if they have another job to add, or say 'done'.",
            data={"saved": job, "total_jobs": len(exp_list)})
        return None

    async def _parse_experience_text(self, text: str) -> dict:
        try:
            response = await gemini_chat(
                system="Extract job experience. Return ONLY valid JSON: "
                       '{"title":"","company":"","period":"","responsibilities":"","achievements":"","city":""}',
                messages=[{"role": "user", "content": text}],
                max_tokens=512, temperature=0.1,
            )
            result = await _parse_json_response(response)
            return result if isinstance(result, dict) else {"responsibilities": text.strip()[:300]}
        except Exception:
            return {"title": "", "company": "", "responsibilities": text.strip()[:300]}

    async def _merge_experience(self, existing: dict, new_text: str) -> dict:
        try:
            response = await gemini_chat(
                system="Merge partial job data with new info. Return ONLY valid JSON: "
                       '{"title":"","company":"","period":"","responsibilities":"","achievements":"","city":""}',
                messages=[{"role": "user",
                           "content": f"Existing: {json.dumps(existing, ensure_ascii=False)}\nNew info: {new_text}"}],
                max_tokens=512, temperature=0.1,
            )
            result = await _parse_json_response(response)
            if isinstance(result, dict):
                for k, v in existing.items():
                    if k not in result or not result[k]:
                        result[k] = v
                return result
        except Exception:
            pass
        existing["responsibilities"] = ((existing.get("responsibilities") or "") + " " + new_text).strip()
        return existing


# ─────────────────────────────────────────────
# 8. EXTRACURRICULAR
# ─────────────────────────────────────────────

class ExtracurricularState(BaseState):
    name = "EXTRACURRICULAR"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Ask about extracurricular activities: volunteering, associations, organized sports, "
            "extra training/certifications. These look great on a CV! They can say 'skip' if none.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})

        intent = await _classify_intent(message_text, {
            "skip": "User has no activities or wants to skip this step",
            "done": "User is finished adding activities (already added some)",
            "content": "User is describing extracurricular activities",
        }, context="Bot asked about extracurricular activities (volunteering, sports, associations). User can skip if none.")

        if intent == "skip":
            return "LANGUAGES"
        if intent == "done" and step_data.get("has_at_least_one"):
            return "LANGUAGES"

        try:
            response = await gemini_chat(
                system="Extract extracurricular activities. Return ONLY valid JSON array: "
                       '[{"activity":"","role":"","organization":"","description":""}]',
                messages=[{"role": "user", "content": message_text}],
                max_tokens=512, temperature=0.1,
            )
            result = await _parse_json_response(response)
            activities = result if isinstance(result, list) else [{"activity": message_text.strip()[:200]}]
        except Exception:
            activities = [{"activity": message_text.strip()[:200]}]

        existing = list(user.extracurricular or [])
        existing.extend(activities)
        crud.update_user(db, user, extracurricular=existing)
        _update_completeness(db, user)

        step_data = dict(ob_state.step_data or {})
        step_data["has_at_least_one"] = True
        crud.update_onboarding_state(db, ob_state, step_data=step_data)

        await respond(wa, phone, user,
            "Activity saved! Ask if they have more or are done.", data={"saved": activities})
        return None


# ─────────────────────────────────────────────
# 9. LANGUAGES
# ─────────────────────────────────────────────

class LanguagesState(BaseState):
    name = "LANGUAGES"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Ask what languages they speak and at what level. "
            "Levels: langue maternelle, courant, intermediaire, debutant. "
            "Common for Moroccans: Arabe, Francais, Anglais, Amazigh, Espagnol. "
            "Ask them to list all languages with levels.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        try:
            response = await gemini_chat(
                system="Extract languages and levels. Return ONLY valid JSON array: "
                       '[{"language":"","level":"maternelle|courant|intermediaire|debutant"}]',
                messages=[{"role": "user", "content": message_text}],
                max_tokens=512, temperature=0.1,
            )
            result = await _parse_json_response(response)
            languages = result if isinstance(result, list) else [{"language": message_text.strip()[:100], "level": "courant"}]
        except Exception:
            languages = [{"language": message_text.strip()[:100], "level": "courant"}]

        crud.update_user(db, user, languages_spoken=languages)
        _update_completeness(db, user)

        await respond(wa, phone, user,
            "Languages saved! Briefly confirm what was recorded.",
            data={"languages": languages})
        return "DRIVING_LICENSE"


# ─────────────────────────────────────────────
# 10. DRIVING_LICENSE
# ─────────────────────────────────────────────

class DrivingLicenseState(BaseState):
    name = "DRIVING_LICENSE"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Ask if they have a driving license. If yes, which category? (A, B, C, D, EC...). "
            "If no, they can say 'no'.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        intent = await _classify_intent(message_text, {
            "no": "User does NOT have a driving license",
            "has_license": "User HAS a driving license (may mention category A, B, C, D, etc.)",
        }, context="Bot asked if user has a driving license and what category")

        if intent == "no":
            crud.update_user(db, user, driving_license="none")
        else:
            text_upper = message_text.strip().upper()
            valid_categories = ["A", "A1", "B", "C", "D", "E", "EB", "EC", "ED"]
            found = [cat for cat in valid_categories if cat in text_upper]
            license_val = ", ".join(found) if found else message_text.strip()[:50]
            crud.update_user(db, user, driving_license=license_val)
            await respond(wa, phone, user,
                f"Driving license saved: {license_val}. Brief confirmation.",
                data={"license": license_val})

        _update_completeness(db, user)
        return "PHOTO"


# ─────────────────────────────────────────────
# 11. PHOTO
# ─────────────────────────────────────────────

class PhotoState(BaseState):
    name = "PHOTO"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Ask if they want to add a professional photo to their CV. "
            "They should send a clear photo (face visible, light background). "
            "They can say 'skip' if they don't want to.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        if media_urls:
            pass  # fall through to photo processing below
        else:
            intent = await _classify_intent(message_text, {
                "skip": "User doesn't want to add a photo, wants to skip",
                "other": "User said something else",
            }, context="Bot asked user to send a professional photo for their CV, or skip")

            if intent == "skip":
                await respond(wa, phone, user, "No problem, they can add a photo later. Moving on.")
                return "INDUSTRY_DETECT"

            await respond(wa, phone, user, "Need a photo image. Ask them to send one or they can skip.")
            return None

        try:
            image_data, content_type = await download_twilio_media(media_urls[0])
            photo_b64 = base64.b64encode(image_data).decode("utf-8")
            crud.update_user(db, user, photo_b64=photo_b64)
            _update_completeness(db, user)
            await respond(wa, phone, user, "Tell the user their photo looks great, it'll be on their CV.")
            return "INDUSTRY_DETECT"

        except Exception as e:
            logger.error(f"Photo download error: {e}", exc_info=True)
            await respond(wa, phone, user, "Problem with the photo. Ask to resend or say 'skip'.")
            return None


# ─────────────────────────────────────────────
# 12. INDUSTRY_DETECT
# ─────────────────────────────────────────────

class IndustryDetectState(BaseState):
    name = "INDUSTRY_DETECT"

    async def enter(self, user, db, wa, phone):
        await respond(wa, phone, user,
            "Tell the user you're now going to figure out their career domain based on their profile. Brief and warm.")

        user_data = {
            "education": user.education or [],
            "experience": user.experience or [],
            "certifications": user.certifications or [],
            "languages_spoken": user.languages_spoken or [],
        }
        result = await detect_industry(user_data)
        category = result.get("industry_category", "fresh_grad")
        sub_category = result.get("sub_category", "")

        crud.update_user(db, user, industry_category=category)

        ob_state_rec = crud.get_onboarding_state(db, user.id)
        if ob_state_rec:
            step_data = dict(ob_state_rec.step_data or {})
            step_data["detection_result"] = result
            crud.update_onboarding_state(db, ob_state_rec, step_data=step_data)

        category_names = {
            "tech": "Tech / Informatique", "executive": "Management / Gestion",
            "trades": "Metiers techniques", "creative": "Creatif / Design",
            "medical": "Medical / Sante", "service": "Service / Commerce",
            "fresh_grad": "Jeune diplome",
        }
        cat_name = category_names.get(category, category)

        await respond(wa, phone, user,
            f"Based on their profile, their career domain seems to be: {cat_name}"
            + (f" ({sub_category})" if sub_category else "")
            + ". Tell them and ask to confirm. If wrong, they can tell you the correct domain.")

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        category = user.industry_category or "fresh_grad"
        intent = await _classify_intent(message_text, {
            "confirm": "User confirms the detected career domain is correct",
            "correct": "User disagrees and wants a different domain, or specifies their actual domain",
        }, context=f"Bot suggested user's career domain is '{category}'. User can confirm or correct.")

        if intent == "confirm":
            _update_completeness(db, user)
            return "INDUSTRY_QA"

        # User disagrees — use AI to detect from their correction + profile
        result = await detect_industry({
            "education": user.education or [],
            "experience": user.experience or [],
            "extra_context": message_text,
        })
        detected = result.get("industry_category", category)

        crud.update_user(db, user, industry_category=detected)
        _update_completeness(db, user)
        return "INDUSTRY_QA"


# ─────────────────────────────────────────────
# 13. INDUSTRY_QA
# ─────────────────────────────────────────────

class IndustryQAState(BaseState):
    name = "INDUSTRY_QA"

    async def enter(self, user, db, wa, phone):
        category = user.industry_category or "fresh_grad"
        questions = get_industry_questions(category)

        ob_state_rec = crud.get_onboarding_state(db, user.id)
        if ob_state_rec:
            step_data = dict(ob_state_rec.step_data or {})
            step_data["questions"] = questions
            step_data["current_q_index"] = 0
            step_data["answers"] = []
            crud.update_onboarding_state(db, ob_state_rec, step_data=step_data)

        await respond(wa, phone, user,
            f"Tell the user you'll now ask {len(questions)} industry-specific questions to strengthen their CV. "
            f"Be encouraging. Then ask the first question: {questions[0] if questions else 'No questions available.'}",
            data={"total_questions": len(questions), "category": category})

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        step_data = dict(ob_state.step_data or {})
        questions = step_data.get("questions", [])
        current_idx = step_data.get("current_q_index", 0)
        answers = step_data.get("answers", [])

        answers.append({
            "question": questions[current_idx] if current_idx < len(questions) else "",
            "answer": message_text.strip(),
        })

        next_idx = current_idx + 1
        step_data["current_q_index"] = next_idx
        step_data["answers"] = answers
        crud.update_onboarding_state(db, ob_state, step_data=step_data)

        if next_idx < len(questions):
            await respond(wa, phone, user,
                f"Acknowledge their answer briefly. Then ask: {questions[next_idx]}",
                data={"question_number": next_idx + 1, "total": len(questions)})
            return None
        else:
            industry_details = dict(user.industry_details or {})
            industry_details["qa_answers"] = answers
            crud.update_user(db, user, industry_details=industry_details)
            _update_completeness(db, user)

            await respond(wa, phone, user,
                "Thank them warmly for answering all the questions. Say their profile is now very strong.")
            return "REVIEW"


# ─────────────────────────────────────────────
# 14. REVIEW
# ─────────────────────────────────────────────

class ReviewState(BaseState):
    name = "REVIEW"

    async def enter(self, user, db, wa, phone):
        summary = self._build_summary(user)
        await respond(wa, phone, user,
            "Show the user a summary of ALL their collected profile data and ask them to confirm "
            "everything is correct. If they want to change something, they can say what. "
            "If everything is good, they say 'ok'.",
            data={"profile_summary": summary})

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        intent = await _classify_intent(message_text, {
            "confirm": "User confirms all profile data is correct, ready to finish",
            "edit": "User wants to change or fix something in their profile",
        }, context="Bot showed a complete profile summary and asked the user to confirm everything is correct")

        if intent == "confirm":
            return "COMPLETE"

        # Parse what they want to edit
        try:
            response = await gemini_chat(
                system="Identify what profile field the user wants to change. Return ONLY valid JSON: "
                       '{"field":"education|experience|languages|driving_license|extracurricular|cin|address|photo|name|other",'
                       '"details":"what they want"}',
                messages=[{"role": "user", "content": message_text}],
                max_tokens=256, temperature=0.1,
            )
            result = await _parse_json_response(response)
            edit_req = result if isinstance(result, dict) else {"field": "other"}
        except Exception:
            edit_req = {"field": "other"}

        field_state_map = {
            "education": "EDUCATION", "experience": "EXPERIENCE",
            "languages": "LANGUAGES", "driving_license": "DRIVING_LICENSE",
            "extracurricular": "EXTRACURRICULAR", "cin": "CIN_FRONT",
            "address": "CIN_BACK", "photo": "PHOTO", "name": "CIN_FRONT",
        }

        redirect_state = field_state_map.get(edit_req.get("field"))
        if redirect_state:
            await respond(wa, phone, user,
                f"The user wants to edit their {edit_req.get('field')}. "
                f"Confirm you'll redo that section and redirect them.")
            return redirect_state
        else:
            await respond(wa, phone, user,
                "Couldn't understand what they want to change. Ask them to be more specific: "
                "'change experience', 'add diploma', 'change name', etc.")
            return None

    def _build_summary(self, user: User) -> dict:
        """Build a structured summary of all collected data."""
        summary = {}
        if user.full_name_latin:
            summary["Nom"] = user.full_name_latin
        if user.cin_number:
            summary["CIN"] = user.cin_number
        if user.date_of_birth:
            summary["Date de naissance"] = user.date_of_birth
        if user.city:
            summary["Ville"] = user.city
        if user.address:
            summary["Adresse"] = user.address
        if user.gender:
            summary["Genre"] = "Homme" if user.gender == "M" else "Femme"

        edu = user.education or []
        if edu:
            summary["Formation"] = [
                f"{e.get('degree_name', '?')} - {e.get('institution', '?')} ({e.get('year', '?')})"
                for e in edu if isinstance(e, dict)
            ]

        exp = user.experience or []
        if exp:
            summary["Experience"] = [
                f"{x.get('title', '?')} @ {x.get('company', '?')} ({x.get('period', '?')})"
                for x in exp if isinstance(x, dict)
            ]

        langs = user.languages_spoken or []
        if langs:
            summary["Langues"] = [f"{l.get('language', '?')} ({l.get('level', '?')})" for l in langs if isinstance(l, dict)]

        if user.driving_license and user.driving_license != "none":
            summary["Permis"] = user.driving_license

        if user.extracurricular:
            summary["Activites"] = [a.get("activity", "?") for a in user.extracurricular if isinstance(a, dict)]

        if user.industry_category:
            summary["Domaine"] = user.industry_category

        summary["Photo"] = "Oui" if user.photo_b64 else "Non"
        summary["Completeness"] = f"{_calc_completeness(user)}%"

        return summary


# ─────────────────────────────────────────────
# 15. COMPLETE
# ─────────────────────────────────────────────

class CompleteState(BaseState):
    name = "COMPLETE"

    async def enter(self, user, db, wa, phone):
        _update_completeness(db, user)
        crud.update_user(db, user, onboarding_complete=True, onboarding_step="COMPLETE")

        name = user.full_name_latin or user.name or ""
        first_name = name.split()[0] if name else ""
        pct = user.profile_completeness or _calc_completeness(user)

        await respond(wa, phone, user,
            f"{'Congratulate ' + first_name + '! ' if first_name else 'Congratulate the user! '}"
            f"Their profile is {pct}% complete. "
            "Tell them what they can do now: "
            "1. Create a professional CV (say 'dir liya CV' or 'creer mon CV') "
            "2. Search for jobs (say 'qlleb liya 3la khdma' or 'chercher emploi') "
            "3. Skills assessment / bilan des competences (say 'bghit bilan' or 'faire un bilan') "
            "4. Ask about ANAPEC services. "
            "Be warm and celebratory! Ask what they want to do first.",
            data={"completeness": pct, "first_name": first_name})

    async def process(self, message_text, media_urls, media_types, user, db, wa, phone, ob_state):
        return "COMPLETE"


# ─────────────────────────────────────────────
# State registry
# ─────────────────────────────────────────────

STATE_CLASSES: dict[str, BaseState] = {
    "WELCOME": WelcomeState(),
    "LANGUAGE_PREF": LanguagePrefState(),
    "COMM_PREF": CommPrefState(),
    "CIN_FRONT": CINFrontState(),
    "CIN_BACK": CINBackState(),
    "EDUCATION": EducationState(),
    "EXPERIENCE": ExperienceState(),
    "EXTRACURRICULAR": ExtracurricularState(),
    "LANGUAGES": LanguagesState(),
    "DRIVING_LICENSE": DrivingLicenseState(),
    "PHOTO": PhotoState(),
    "INDUSTRY_DETECT": IndustryDetectState(),
    "INDUSTRY_QA": IndustryQAState(),
    "REVIEW": ReviewState(),
    "COMPLETE": CompleteState(),
}

STATE_ORDER = [
    "WELCOME", "LANGUAGE_PREF", "COMM_PREF", "CIN_FRONT", "CIN_BACK",
    "EDUCATION", "EXPERIENCE", "EXTRACURRICULAR", "LANGUAGES",
    "DRIVING_LICENSE", "PHOTO", "INDUSTRY_DETECT", "INDUSTRY_QA",
    "REVIEW", "COMPLETE",
]


def get_state(name: str) -> BaseState | None:
    return STATE_CLASSES.get(name)
